# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks: []
builds:
  - main: ./cmd/goaegis
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -X main.version={{.Version}}
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}"
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
changelog:
  disable: false
gitea_urls:
  api: https://gitea.dwysokinski.me/api/v1
  download: https://gitea.dwysokinski.me
