when:
  event: tag
  ref: refs/tags/v*

variables:
  - &goreleaser_image 'goreleaser/goreleaser:v1.25.1'

steps:
  release:
    image: *goreleaser_image
    depends_on:
      - generate
    commands:
      - goreleaser release --clean
    secrets:
      - gitea_token
